name: Build project

on:
    push:
        paths:
            - "**.cpp"
            - "**.hpp"
            - "CMakeLists.txt"
            - ".github/workflows/**/*"
            - "build.sh"

jobs:
    linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Set up the Intel oneAPI Docker container
            - name: Set up Intel oneAPI container
              uses: addnab/docker-run-action@v3
              with:
                  image: intel/oneapi-hpckit:latest
                  shell: bash
                  options: -v ${{ github.workspace }}:/workspace -e CI=1 --rm # Remove the container after execution
                  # Inside the container, run build commands
                  run: |
                      # Change to the workspace directory
                      cd /workspace

                      # TEMPORARY: remove GPU builds from CI
                      sed -i '/# GPU/,$d' CMakeLists.txt

                      # execute build script
                      bash build.sh
